### ISSUE TITLE
章节认领

### ISSUE THREAD

**Issue by FMX** [apachecn/flink-doc-zh#18]
Checkpoints

**Comment by FMX** [comment]
@zyBourn  
请问一下：
1.能自由参与吗？
2.翻译的结果放到哪里？

**Comment by jiangzhonglian** [comment]
比你想象中更自由，结果可以模仿翻译的人就行！

留言格式：昵称 + QQ + 章节
参考这里：https://github.com/apachecn/flink-doc-zh/issues/13
